name: Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build
        run: yarn && yarn build && yarn docs:build

      - name: Tests
        run: yarn test
