name: Daily update notepad2web
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  build:
    name: Update notepad2web
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: update notepad2web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm i && npx vite build && go run . -extract-notepad2 -ci
